PLAYFIELD_WIDTH = 10
PLAYFIELD_HEIGHT = 20
 
PLAYFIELD_XOFFSET = 100
PLAYFIELD_YOFFSET = 100

BLOCK_WIDTH= 16
BLOCK_HEIGHT= 16

ROW_DESTROY_TIME=1

FALL_SPEED = 0.5
MAX_FALL_SPEED = 0.02

TetrominoFallTimer = 0